spring:
  datasource:
    url: jdbc:mysql://192.168.0.142:3306/logistics?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    pool:
     max-active: 300
     min-idle: 0
     max-wait: 10000
     max-idle: 100
     timeout: 5000
    host: 192.168.0.142
    password: 123456
    database: 1
    port: 6379
ftp:
  clientTimeout: 10000
  encoding: UTF-8
  passiveMode: true
  host: 192.168.0.142
  port: 21
  username: admin
  password: 123456

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
mapper:
    not-empty: false
    identity: MYSQL

upload:
  file:
    dir: d:/tmp